//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelim.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtelDBEntities4 : DbContext
    {
        public OtelDBEntities4()
            : base("name=OtelDBEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Müşteri> Müşteri { get; set; }
        public virtual DbSet<Oda> Oda { get; set; }
        public virtual DbSet<Rezervasyonlar> Rezervasyonlar { get; set; }
    }
}
