//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otelim.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyonlar
    {
        public int id { get; set; }
        public int odaid { get; set; }
        public int musteriid { get; set; }
        public System.DateTime giristarihi { get; set; }
        public System.DateTime cikistarihi { get; set; }
        public string durum { get; set; }
    
        public virtual Müşteri Müşteri { get; set; }
        public virtual Oda Oda { get; set; }
    }
}
